version: '3'
services:
  web_t2:
    image: java_springv1_t2
    build: .
    ports:
      - "8092:8085"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/crimebusters/volumes
